# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

      - run: yarn build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - public
  deploy-develop:
    docker:
      - image: cibuilds/aws:1.16.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to Deloitte Digital
          command: aws s3 sync public s3://develop.swth.deloittedigital.co.uk --delete
      - run:
          name: Deploy to Deloitte
          command: aws s3 sync public s3://develop.swth.deloitte.co.uk --delete
  deploy-master:
    docker:
      - image: cibuilds/aws:1.16.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to Deloitte Digital
          command: aws s3 sync public s3://swth.deloittedigital.co.uk --delete
      - run:
          name: Deploy to Deloitte
          command: aws s3 sync public s3://swth.deloitte.co.uk --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-develop:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy-master:
          requires:
            - build
          filters:
            branches:
              only: master